mysite/file_uploader/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.fileUploaderView)
]

mysite/login/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^login/', views.login, name='login'),
    re_path(r'^logout/', views.logout, name='logout'),
    re_path(r'^signup/', views.signup, name='signup'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import re_path
from django.conf.urls import include

urlpatterns = [
    re_path(r'^login/', include('login.urls')),
    re_path(r'^polls/', include('polls.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^file-upload/', include('file_uploader.urls')),
    re_path(r'^pagination/', include('pagination.urls')),
]

mysite/pagination/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.listing)
]

mysite/polls/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    #re_path(r'^$',views.index, name='index'),
    #re_path(r'^(?P<question_id>[0-9]+)/$', views.detail, name ='detail'),  
    #re_path(r'^(?P<question_id>[0-9]+)/results/$', views.result, name ='result'),
    #re_path(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name ='vote'),

    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name ='detail'),  
    re_path(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name ='results'),  
    re_path(r'^(?P<pk>[0-9]+)/vote/$', views.vote, name ='vote'),  
]

mysite/file_uploader/models.py
from django.db import models

# Create your models here.
#from django.forms import ModelForm
#
#TITLE_CHOICES = (
#    ('MR', 'Mr.'),
#    ('MRS', 'Mrs.'),
#    ('MS', 'Ms.'),
#)
#
#class Author(models.Model):
#    name = models.CharField(max_length=100)
#    title = models.CharField(max_length=3, choices= TITLE_CHOICES)
#    birth_day = models.DateField(blank=True, null=True)
#
#class Book(models.Model):
#    name = models.CharField(max_length=100)
#    author = models.ManyToManyField(Author)
#
#class AuthorForm(ModelForm):
#    class Meta:
#        model = Author
#        fields = ['name', 'title', 'birth_date']
#
#class BookForm(ModelForm):
#    class Meta:
#        model = Book
#        fields = ['name', 'authors']
            

mysite/login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username

mysite/pagination/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=20)

mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=250)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text  = models.CharField(max_length=250)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        

mysite/file_uploader/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

    

mysite/file_uploader/views.py
from django.shortcuts import render
from django.db import models

# Create your views here.
from django.http import HttpResponse
from .forms import UploadFileForm

def fileUploaderView(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            upload(request.FILES['file'])
            return HttpResponse("<h2>Uploaded file successfully</h2>")
        else:
            return HttpResponse("<h2>Uploaded file not successfully</h2>")
        
    form = UploadFileForm()
    return render(request, 'fileUploaderTemplate.html', {'form' : form})



def upload(f):
    file = open(f.name, 'wb+')
    for chunk in f.chunks():
        file.write(chunk)

mysite/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User

# Create your views here.
def home(request):
    if 'user' in request.session:
        current_user = request.session['user']
        param = {'current_user' : current_user}
        return render(request, 'base.html', param)
    else:
        return redirect('login')
    return render(request, 'login.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if User.objects.filter(username=username).count() > 0:
            return HttpResponse('Username already exists')
        else:
            user = User(username = username, password = password)
            user.save()
            return redirect('login')
    else:
        return render(request, 'signup.html')   
    
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        check_user = User.objects.filter(username = username, password = password)
        if check_user:
            request.session['user'] = username
            return redirect('home')
        else:
            return HttpResponse('Please enter valid Username or Password')
    return render(request, 'login.html')

def logout(request):
    try:
        del request.session['user']
    except:
        return redirect('login')
    return redirect('login')

mysite/pagination/views.py
from django.shortcuts import render

# Create your views here.
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Customer

def listing(request):
    customer_list = Customer.objects.all()
    paginator = Paginator(customer_list, 5)

    pageNumber = request.GET.get('page')
    try:
        customers = paginator.page(pageNumber)
    except PageNotAnInteger:
        customers = paginator.page(1)
    except EmptyPage:
        customers = paginator.page(paginator.num_pages)

    return render(request, 'list.html',{'customers' : customers})

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.views import generic
from django.urls import reverse

# Create your views here.

#def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    output = ',   '.join([q.question_text for q in latest_question_list])
#    return HttpResponse(output)
#
#def detail(request, question_id):
#    return HttpResponse("You're looking at question %s." % question_id)
#
#def result(request, question_id):
#    response = "You're looking at the result of question %s."
#    return HttpResponse(response % question_id)
#
#def vote(request, question_id):
#    return HttpResponse("You're voting on question %s." % question_id)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lastest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set_get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message': "You didn't select a choice"
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id)))
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

        
    

mysite/file_uploader/templates/fileUploaderTemplate.html
<!DOCTYPE html>
<html>
    <head>
        <title>Upload File</title>
    </head>
    <body>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
    </body>
</html>

mysite/login/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>
    <body>
        <h1>My Site</h1>

        <a href="/">Home</a>
        <span>/</span>

        {% if current_user %}
            <a href="{% url 'logout' %}">Logout</a>
            <hr>
            <h2>Welcome <span style="color :blue">{{ current_user}}</span></h2>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <span>/</span>
            <a href="{% url 'signup' %}">Sign Up</a>
            <hr>
            <h2>Login to access this website!</h2>
        {% endif %}

        {% block body %}
        {% endblock %}
    </body>
</html>

mysite/login/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="User Name">
        <br>
        <input type="text" name="password" placeholder="Password">
        <br>
        <input type="submit" name="submit" value="Login">
    </form>

{% endblock %}

mysite/login/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}

{% block body %}
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="User Name">
        <br>
        <input type="text" name="password" placeholder="Password">
        <br>
        <input type="submit" name="submit" value="Sign Up">
    </form>

{% endblock %}

mysite/pagination/templates/list.html
<!DOCTYPE>
<html>

    <head>
        <title>Phan Trang</title>
    </head>
    <body>
        <table border="1px solid #000">
            <tr>
                <th>Customer Name</th>
                <th>Country</th>
            </tr>
            {% for customer in customers %}
            <tr>
                <td>{{ customer.name }}</td>
                <td>{{ customer.country }}</td>
            </tr>
            {% endfor %}
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if customers.has_previous %}
                    <a href="?page={{ customers.previous_page_number }}">Previous</a>
                {% endif %}
            </span>

            <span class="current">
                Page {{ customers.number }} of {{ customers.paginators.num_pages }}    
            </span>

            <span>
                {% if customers.has_next %}
                    <a href="?page={{ customers.next_page_number }}"> Next</a>
                {% endif %}
            </span>

        </div>
    </body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
    <header>
        <title> CHI TIET CAC CAU HOI</title>
    </header>
    <body>
            <h1>{{question.question_text}}</h1>
        
            {% if error_message %}
                <strong>{{ error_message}}</strong>
            {% endif %}

            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{choice.id}}"/>
                    <label for="choice{{ forloop.counter}}">{{ choice.choice_text}}</label>
                {% endfor %}
                <input type="submit" value="Vote"/>
            </form>
    </body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
    <header>
        <title> DANH SACH CAC CAU HOI</title>
    </header>
    <body>
        <h1>DANH SACH CAC CAU HOI</h1>
        {% if lastest_question_list %}
            <ul>
                {% for question in lastest_question_list  %}
                    <li>
                        <a href="/polls/{{question.id}}/">
                            {{ question.question_text }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
        {% endif %}
    </body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
    <header>
        <title> DANH SACH CAC CAU HOI</title>
    </header>
    <body>
        <h1>{% question.question_text %}</h1>
        {% question.question_text %}
        <ul>
            {% for choice in question.choice_set.all  %}
                <li>
                    {{ choice.choice_text}} -- {{ choice.votes}} vote{{ choice.votes | pluralize }} 
                </li>
            {% endfor %}
        </ul>
        {% endfor %}

        <a href="{% url 'polls:detail' question.id %}">Vote again ?</a>
    </body>
</html>